# Base values file for the Helm chart

replicaCount: 2

mysql:
  image: "mysql:5.7"
  rootPassword: "Msois@123"
  database: "mom_pop_db"
  user: "root"

cafeweb:
  image: "amulya2503/mompopcafeapp"
  tag: "v1"

persistentVolume:
  storageSize: "20Gi"
  hostPath: "/mnt/data/default"

service:
  type: NodePort
  port: 80

nodeSelector: {}

tolerations: []

affinity: []

config:
  showServerInfo: "false"
  timeZone: "America/New_York"
  currency: "$"
