replicaCount: 1

mysql:
  image: mysql:latest
  database: mom_pop_db
  user: root

cafeweb:
  image: amulya2503/mompopcafeapp:v1
  tag: v1

persistentVolume:
  size: 10Gi
  hostPath: "/mnt/data/dev"

config:
  showServerInfo: "false"
  timeZone: "America/New_York"
  currency: "$"
  db_url: "mysql"
  db_name: "mom_pop_db"
  db_user: "root"
  db_password: "Msois@123"

