# Base values file for the Helm chart

replicaCount: 2

mysql:
  image: "mysql:latest"
  rootPassword: "Msois@123"
  database: "mom_pop_db"
  user: "root"

cafeweb:
  image: "amulya2503/mompopcafeapp"
  tag: "v1"

persistentVolume:
  storageSize: "20Gi"
  hostPath: "/mnt/data/default"

service:
  type: NodePort
  port: 80

nodeSelector: {}

tolerations: []

affinity: []

config:
  getAppParameters.php: |
    <?php
      $showServerInfo = "false";
      $timeZone = "America/New_York";
      $currency = "$";
      $db_url = "{{ .Release.Name }}-mysql";
      $db_name = "mom_pop_db";
      $db_user = "root";
      $db_password = "Msois@123";
    ?>

