apiVersion: v1
kind: Service
metadata:
  name: {{ include "mompopcafe.fullname" . }}-web
  labels:
    app: {{ include "mompopcafe.fullname" . }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: 80
      {{- if .Values.service.web.nodePort }}
      nodePort: {{ .Values.service.web.nodePort }}
      {{- end }}
  selector:
    app: {{ include "mompopcafe.fullname" . }}
    tier: frontend
