apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.serviceName }}
  labels:
    app: {{ include "mompopcafe.fullname" . }}
spec:
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
  selector:
    app: {{ include "mompopcafe.fullname" . }}
    tier: mysql
  {{- if .Values.mysql.headless }}
  clusterIP: None
  {{- end }}
