{{- if .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mompopcafe.fullname" . }}-mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.persistence.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysql.persistence.hostPath | quote }}
---
{{- end }}
